### ISSUE TITLE
cant use ScrollController

### ISSUE THREAD

**Issue by ggugyi96** [dridino/smooth_list_view#1]
cant use ScrollController with SmoothListView.build

**Comment by dridino** [comment]
> cant use ScrollController with SmoothListView.build

Can you provide an example that doesn't work so I can replicate your issue ? Because it seems to work.

**Comment by ggugyi96** [comment]
Expanded(
            child: Container(
              clipBehavior: Clip.antiAlias,
              margin: const EdgeInsets.fromLTRB(25, 0, 25, 25),
              padding: const EdgeInsets.fromLTRB(5, 5, 5, 5),
              decoration: BoxDecoration(
                  borderRadius: BorderRadius.circular(4),
                  color: ColorConfig.widgetColor),
              child: user.gameHistoryList.isNotEmpty
                  ? EasyRefresh(
                      controller: easyRefreshController,
                      refreshOnStart: user.isFirstLoad.value,
                      header: const ClassicHeader(),
                      footer: const ClassicFooter(),
                      onRefresh: onRefresh,
                      onLoad: onLoadMore,
                      child: SmoothListView.builder(
                        smoothScroll: true,
                        curve: Curves.linear,
                        duration: const Duration(milliseconds: 200),
                        controller: _scrollController,
                        itemCount: user.gameHistoryList.length,
                        itemBuilder: (context, index) {
                          return ProfileMatchTile.matchHisTileByQueueId(
                              user.gameHistoryList[index]);
                        },
                      ),
                    )
                  : const Center(
                      child: MText(text: 'No match history'),
                    ),
            ),
          )

**Comment by dridino** [comment]
> Expanded( child: Container( clipBehavior: Clip.antiAlias, margin: const EdgeInsets.fromLTRB(25, 0, 25, 25), padding: const EdgeInsets.fromLTRB(5, 5, 5, 5), decoration: BoxDecoration( borderRadius: BorderRadius.circular(4), color: ColorConfig.widgetColor), child: user.gameHistoryList.isNotEmpty ? EasyRefresh( controller: easyRefreshController, refreshOnStart: user.isFirstLoad.value, header: const ClassicHeader(), footer: const ClassicFooter(), onRefresh: onRefresh, onLoad: onLoadMore, child: SmoothListView.builder( smoothScroll: true, curve: Curves.linear, duration: const Duration(milliseconds: 200), controller: _scrollController, itemCount: user.gameHistoryList.length, itemBuilder: (context, index) { return ProfileMatchTile.matchHisTileByQueueId( user.gameHistoryList[index]); }, ), ) : const Center( child: MText(text: 'No match history'), ), ), )

Could you be more specific about the `ScrollController` feature that doesn't work ? I tried to use that piece of code, removed all your custom widgets etc and I'm able to use a `ScrollController` to scroll the list using the `animateTo` method. So unless you can provide a clear example of what you're trying to achieve and doesn't work because of the package, I can't help you any further.

PS : You might want to pay attention to the `Incorrect use of ParentDataWidget.` error you have too.

**Comment by ggugyi96** [comment]
cant drag scrollbar

![2b9e2bd058b4577db0f6ff246cce5de1](https://github.com/user-attachments/assets/f03aa491-d7f0-4fac-b7a2-64f96027278e)

**Comment by ggugyi96** [comment]
cant drag scrollbar

https://github.com/user-attachments/assets/e20701d2-e796-4b41-a3f7-e89e798e71e2

**Comment by dridino** [comment]
> cant drag scrollbar

Indeed, I just published a new version that should fix it, let me know if it works now.
