### ISSUE TITLE
Scrollbar seems to not be functioning, in Windows environment.

### ISSUE THREAD

**Issue by Sukiet** [dridino/smooth_list_view#2]

**Comment by Sukiet** [comment]
hello @dridino , im testing this in Windows and found Scrollbar cant be dragged by mouse

**Comment by dridino** [comment]
> hello @dridino , im testing this in Windows and found Scrollbar cant be dragged by mouse

Hello, I just tried using the example project from the repo and it seems to work as expected, on Windows10 with an external mouse, with smoothScroll enabled or disabled.
It was an issue a few weeks ago though, so make sure you have the updated version of the package :)

**Comment by Sukiet** [comment]
hello @dridino , tkx for ur patience. Though im sure using the updated version 1.1.0 and i saw the closed issue and the Changelog on pub.dev. It seems still a problem for me:



https://github.com/user-attachments/assets/3f8a79b5-74a4-4b31-b0a0-5e7c77726b0e

**Comment by Sukiet** [comment]
```dart
class DailyView extends StatefulWidget {
  const DailyView({super.key});

  @override
  State<DailyView> createState() => _DailyViewState();
}

class _DailyViewState extends State<DailyView> {
  @override
  Widget build(BuildContext context) {
    return SmoothListView.builder(
      duration: Duration(milliseconds: 300),
      itemCount: 50,
      itemBuilder: (context, index) {
        return ListTile(title: Text("list - $index", style: SukietDarkTheme.textStyle),);
      });
  }
}
```
Sry, I don't know why the video I uploaded is black screen.....this is my widget using SmoothListView.builder.

**Comment by Sukiet** [comment]
i tested your example/lib/main.dart and it works fine. Maybe due to the ScrollBar wrapping the SmoothListView.builder 👇
```dart
Scrollbar(
  controller: controller,
  thumbVisibility: true,
  child: SmoothListView.builder(
    smoothScroll: smooth,
    duration: const Duration(milliseconds: 200),
    controller: controller,
    itemCount: 20,
    itemBuilder: (ctx, idx) {
      return Container(
        height: 200,
        width: 200,
        color: colorList[idx % colorList.length],
        child: Center(child: Text("$idx")),
      );
    },
  ),
),
```
So it is necessary to use a scrollbar for wrapping in order to run, right？

**Comment by dridino** [comment]
Hello @Sukiet , I published a fix a few minutes ago. You can now use the `Scrollbar` as expected on desktop without having to wrap your `SmoothListView` in a `Scrollbar` widget.
Let me know if you encounter any issue

**Comment by Sukiet** [comment]
Thank you so much. it runs great. This is the most convenient smooth scrolling implementation I've used in a desktop environment 🥇 :)

**Comment by dridino** [comment]
> Thank you so much. it runs great. This is the most convenient smooth scrolling implementation I've used in a desktop environment 🥇 :)

Thanks, I'm glad you like it !

**Comment by dridino** [comment]
Thanks, I'm glad you like it !
