### ISSUE TITLE
Impossible to Interact

### ISSUE THREAD

**Issue by JLdevFr** [dridino/smooth_list_view#3]
When "smooth" is enabled, it becomes impossible to interact with elements inside the listview (e.g., buttons are not clickable). I tested this directly on your example code.

**Comment by dridino** [comment]
> When "smooth" is enabled, it becomes impossible to interact with elements inside the listview (e.g., buttons are not clickable). I tested this directly on your example code.

Hello, thanks for submitting this issue, I'm working on fixing it as soon as possible.

**Comment by JLdevFr** [comment]
Hi, Have you made any progress on this issue? :)

**Comment by dridino** [comment]
> Hi, Have you made any progress on this issue? :)

Hi, I actually have, I should be pushing a fix in a few days, I'm still testing it and making sure everything is working as expected. Thanks for your patience :)

**Comment by dridino** [comment]
Good evening @JLdevFr, I'm happy to tell you that a fix has been published to pub a few seconds ago, you are now able to interact with widgets inside the `SmoothListView`. Thank you for your patience and let me know if you still encounter any problem with the package :)
