### ISSUE TITLE
Having `reversed: true` causes incorrect scrolling direction with mousewheel

### ISSUE THREAD

**Issue by Tech-Tac** [dridino/smooth_list_view#4]
I have a list like this:
```dart
SmoothListView.builder(
    reverse: true, // <- culprit here
    smoothScroll: true,
    duration: const Duration(milliseconds: 250),
    itemCount: messages.length,
    itemBuilder: (listContext, index) {...}
)
```
Where if you scroll down it scrolls up and vice versa, setting reverse to false results in expected behavior.

**Comment by dridino** [comment]
Thank you for submitting this issue. The version I just published solves this, let me know if everything works for you, that way I can close the issue :)

**Comment by Tech-Tac** [comment]
Yes, it seems to be fixed, and the other issue too. Thanks for the quick fix.

**Comment by dridino** [comment]
No problem, my pleasure, have a nice day
